export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export const THEME_INFO = {
  light: { icon: "☀️", category: "Standard" },
  dark: { icon: "🌙", category: "Standard" },
  cupcake: { icon: "🧁", category: "Colorful" },
  bumblebee: { icon: "🐝", category: "Colorful" },
  emerald: { icon: "💎", category: "Colorful" },
  corporate: { icon: "🏢", category: "Professional" },
  synthwave: { icon: "🌈", category: "Retro" },
  retro: { icon: "📺", category: "Retro" },
  cyberpunk: { icon: "🤖", category: "Futuristic" },
  valentine: { icon: "💕", category: "Seasonal" },
  halloween: { icon: "🎃", category: "Seasonal" },
  garden: { icon: "🌻", category: "Nature" },
  forest: { icon: "🌲", category: "Nature" },
  aqua: { icon: "🌊", category: "Nature" },
  lofi: { icon: "🎵", category: "Mood" },
  pastel: { icon: "🎨", category: "Soft" },
  fantasy: { icon: "🦄", category: "Soft" },
  wireframe: { icon: "📐", category: "Minimal" },
  black: { icon: "⚫", category: "Minimal" },
  luxury: { icon: "💰", category: "Premium" },
  dracula: { icon: "🦇", category: "Dark" },
  cmyk: { icon: "🖨️", category: "Print" },
  autumn: { icon: "🍂", category: "Seasonal" },
  business: { icon: "💼", category: "Professional" },
  acid: { icon: "🧪", category: "Vibrant" },
  lemonade: { icon: "🍋", category: "Fresh" },
  night: { icon: "🌃", category: "Dark" },
  coffee: { icon: "☕", category: "Warm" },
  winter: { icon: "❄️", category: "Cool" },
  dim: { icon: "🔅", category: "Subdued" },
  nord: { icon: "🧊", category: "Cool" },
  sunset: { icon: "🌅", category: "Warm" },
};